package com.organizer.chat.util

object EmojiUtils {

    private val EMOTICON_MAP = mapOf(
        ":-)" to "😊",
        ":)" to "😊",
        ":-(" to "😞",
        ":(" to "😞",
        ":-D" to "😃",
        ":D" to "😃",
        ":-d" to "😃",
        ":d" to "😃",
        ":-P" to "😛",
        ":P" to "😛",
        ":-p" to "😛",
        ":p" to "😛",
        ":-/" to "😕",
        ":/" to "😕",
        ":-O" to "😮",
        ":O" to "😮",
        ":-o" to "😮",
        ":o" to "😮",
        ":-*" to "😘",
        ":*" to "😘",
        ";-)" to "😉",
        ";)" to "😉",
        "B-)" to "😎",
        "B)" to "😎",
        "<3" to "❤️",
        "xD" to "😆",
        "XD" to "😆",
        "xd" to "😆",
        ":xD" to "😆",
        ":XD" to "😆",
        ":xd" to "😆",
        "^^" to "😊",
        "Xd" to "😆",
        "=)" to "😊",
        "=D" to "😃",
        "=d" to "😃",
        "=(" to "😞",
        "=/" to "😕",
        "=P" to "😛",
        "=p" to "😛",
        "=O" to "😮",
        "=o" to "😮",
        ":'(" to "😢",
        ":'-(" to "😢",
        ":-|" to "😐",
        ":|" to "😐",
        "-_-" to "😑",
        ">:(" to "😠",
        ">:-(" to "😠",
        "o_o" to "😳",
        "O_O" to "😳",
        "</3" to "💔",
        "b-)" to "😎",
        "b)" to "😎",
        ":-]" to "😊",
        ":]" to "😊",
        ":-[" to "😞",
        ":[" to "😞",
        "lol" to "lol 😆",
        "LOL" to "LOL 😆",
        "Lol" to "Lol 😆",
        "mdr" to "mdr 😆",
        "MDR" to "MDR 😆",
        "Mdr" to "Mdr 😆",
    )

    private val SHORTCODE_MAP = mapOf(
        // Smileys & People
        "smile" to "😊",
        "laughing" to "😆",
        "blush" to "😊",
        "smiley" to "😃",
        "relaxed" to "☺️",
        "smirk" to "😏",
        "heart_eyes" to "😍",
        "kissing_heart" to "😘",
        "kissing" to "😗",
        "wink" to "😉",
        "stuck_out_tongue_winking_eye" to "😜",
        "stuck_out_tongue" to "😛",
        "flushed" to "😳",
        "grinning" to "😀",
        "grin" to "😁",
        "joy" to "😂",
        "rofl" to "🤣",
        "sweat_smile" to "😅",
        "sob" to "😭",
        "cry" to "😢",
        "angry" to "😠",
        "rage" to "😡",
        "triumph" to "😤",
        "sleepy" to "😪",
        "yum" to "😋",
        "mask" to "😷",
        "sunglasses" to "😎",
        "dizzy_face" to "😵",
        "imp" to "👿",
        "smiling_imp" to "😈",
        "neutral_face" to "😐",
        "no_mouth" to "😶",
        "innocent" to "😇",
        "alien" to "👽",
        "yellow_heart" to "💛",
        "blue_heart" to "💙",
        "purple_heart" to "💜",
        "heart" to "❤️",
        "green_heart" to "💚",
        "broken_heart" to "💔",
        "heartbeat" to "💓",
        "heartpulse" to "💗",
        "sparkling_heart" to "💖",
        "cupid" to "💘",
        "revolving_hearts" to "💞",
        "thinking" to "🤔",
        "thinking_face" to "🤔",
        "skull" to "💀",
        "poop" to "💩",
        "ghost" to "👻",
        "eyes" to "👀",
        "tongue" to "👅",
        "pleading_face" to "🥺",
        "face_with_tears_of_joy" to "😂",
        "upside_down_face" to "🙃",
        "money_mouth_face" to "🤑",
        "nerd_face" to "🤓",
        "hugs" to "🤗",
        "shush" to "🤫",
        "shushing_face" to "🤫",
        "zipper_mouth_face" to "🤐",
        "raised_eyebrow" to "🤨",
        "monocle_face" to "🧐",
        "grimacing" to "😬",
        "rolling_eyes" to "🙄",
        "exploding_head" to "🤯",
        "partying_face" to "🥳",
        "woozy_face" to "🥴",
        "hot_face" to "🥵",
        "cold_face" to "🥶",
        "clown_face" to "🤡",
        "yawning_face" to "🥱",
        "saluting_face" to "🫡",
        "melting_face" to "🫠",

        // Gestures
        "thumbsup" to "👍",
        "+1" to "👍",
        "thumbsdown" to "👎",
        "-1" to "👎",
        "ok_hand" to "👌",
        "punch" to "👊",
        "fist" to "✊",
        "v" to "✌️",
        "wave" to "👋",
        "hand" to "✋",
        "open_hands" to "👐",
        "point_up" to "☝️",
        "point_down" to "👇",
        "point_left" to "👈",
        "point_right" to "👉",
        "raised_hands" to "🙌",
        "pray" to "🙏",
        "clap" to "👏",
        "muscle" to "💪",
        "metal" to "🤘",
        "middle_finger" to "🖕",
        "writing_hand" to "✍️",
        "handshake" to "🤝",
        "crossed_fingers" to "🤞",
        "pinching_hand" to "🤏",
        "love_you_gesture" to "🤟",
        "call_me_hand" to "🤙",
        "brain" to "🧠",

        // Nature & Animals
        "dog" to "🐶",
        "cat" to "🐱",
        "mouse" to "🐭",
        "hamster" to "🐹",
        "rabbit" to "🐰",
        "bear" to "🐻",
        "panda_face" to "🐼",
        "chicken" to "🐔",
        "penguin" to "🐧",
        "bird" to "🐦",
        "monkey_face" to "🐵",
        "see_no_evil" to "🙈",
        "hear_no_evil" to "🙉",
        "speak_no_evil" to "🙊",
        "pig" to "🐷",
        "frog" to "🐸",
        "snake" to "🐍",
        "turtle" to "🐢",
        "unicorn" to "🦄",
        "bee" to "🐝",
        "bug" to "🐛",
        "butterfly" to "🦋",
        "fish" to "🐟",
        "whale" to "🐳",
        "dolphin" to "🐬",
        "octopus" to "🐙",
        "fox_face" to "🦊",
        "wolf" to "🐺",
        "lion" to "🦁",

        // Nature & Weather
        "sun" to "☀️",
        "sunny" to "☀️",
        "cloud" to "☁️",
        "snowflake" to "❄️",
        "zap" to "⚡",
        "rainbow" to "🌈",
        "star" to "⭐",
        "star2" to "🌟",
        "sparkles" to "✨",
        "moon" to "🌙",
        "earth_americas" to "🌎",
        "fire" to "🔥",
        "boom" to "💥",
        "droplet" to "💧",
        "ocean" to "🌊",
        "leaves" to "🍃",
        "fallen_leaf" to "🍂",
        "herb" to "🌿",
        "cherry_blossom" to "🌸",
        "rose" to "🌹",
        "sunflower" to "🌻",
        "hibiscus" to "🌺",
        "tulip" to "🌷",
        "seedling" to "🌱",
        "evergreen_tree" to "🌲",
        "cactus" to "🌵",
        "mushroom" to "🍄",

        // Food & Drink
        "pizza" to "🍕",
        "hamburger" to "🍔",
        "fries" to "🍟",
        "beer" to "🍺",
        "beers" to "🍻",
        "wine_glass" to "🍷",
        "coffee" to "☕",
        "tea" to "🍵",
        "cake" to "🍰",
        "cookie" to "🍪",
        "chocolate_bar" to "🍫",
        "apple" to "🍎",
        "banana" to "🍌",
        "watermelon" to "🍉",
        "grapes" to "🍇",
        "strawberry" to "🍓",
        "peach" to "🍑",
        "popcorn" to "🍿",
        "icecream" to "🍦",
        "taco" to "🌮",
        "burrito" to "🌯",
        "egg" to "🥚",
        "avocado" to "🥑",
        "croissant" to "🥐",

        // Objects & Symbols
        "100" to "💯",
        "checkmark" to "✔️",
        "white_check_mark" to "✅",
        "x" to "❌",
        "cross_mark" to "❌",
        "warning" to "⚠️",
        "exclamation" to "❗",
        "question" to "❓",
        "bulb" to "💡",
        "wrench" to "🔧",
        "hammer" to "🔨",
        "gear" to "⚙️",
        "link" to "🔗",
        "key" to "🔑",
        "lock" to "🔒",
        "unlock" to "🔓",
        "bell" to "🔔",
        "bookmark" to "🔖",
        "paperclip" to "📎",
        "scissors" to "✂️",
        "pencil" to "✏️",
        "pen" to "🖊️",
        "book" to "📖",
        "memo" to "📝",
        "clipboard" to "📋",
        "calendar" to "📅",
        "pushpin" to "📌",
        "mag" to "🔍",
        "flashlight" to "🔦",

        // Transport & Travel
        "rocket" to "🚀",
        "airplane" to "✈️",
        "car" to "🚗",
        "taxi" to "🚕",
        "bus" to "🚌",
        "bike" to "🚲",
        "train" to "🚆",
        "ship" to "🚢",
        "anchor" to "⚓",
        "house" to "🏠",

        // Activities & Sports
        "soccer" to "⚽",
        "basketball" to "🏀",
        "football" to "🏈",
        "baseball" to "⚾",
        "tennis" to "🎾",
        "trophy" to "🏆",
        "medal" to "🏅",
        "crown" to "👑",
        "gem" to "💎",
        "guitar" to "🎸",
        "microphone" to "🎤",
        "headphones" to "🎧",
        "video_game" to "🎮",
        "dart" to "🎯",
        "tada" to "🎉",
        "confetti_ball" to "🎊",
        "balloon" to "🎈",
        "gift" to "🎁",
        "art" to "🎨",
        "ribbon" to "🎀",
        "movie_camera" to "🎥",
        "camera" to "📷",

        // Flags & Misc
        "flag_fr" to "🇫🇷",
        "flag_us" to "🇺🇸",
        "flag_gb" to "🇬🇧",
        "flag_de" to "🇩🇪",
        "flag_es" to "🇪🇸",
        "flag_it" to "🇮🇹",
        "flag_jp" to "🇯🇵",

        // Tech
        "computer" to "💻",
        "iphone" to "📱",
        "keyboard" to "⌨️",
        "robot" to "🤖",
        "satellite" to "🛰️",
        "electric_plug" to "🔌",
        "battery" to "🔋",
        "cd" to "💿",
        "floppy_disk" to "💾",

        // Hearts & Love
        "two_hearts" to "💕",
        "gift_heart" to "💝",
        "heart_decoration" to "💟",
        "heavy_heart_exclamation" to "❣️",
        "love_letter" to "💌",
        "kiss" to "💋",
        "ring" to "💍",
        "bouquet" to "💐",
        "couple" to "👫",

        // Misc popular
        "zzz" to "💤",
        "anger" to "💢",
        "sweat_drops" to "💦",
        "notes" to "🎶",
        "musical_note" to "🎵",
        "no_entry" to "⛔",
        "stop_sign" to "🛑",
        "construction" to "🚧",
        "rotating_light" to "🚨",
        "loudspeaker" to "📢",
        "mega" to "📣",
        "speech_balloon" to "💬",
        "thought_balloon" to "💭",
        "wave_dash" to "〰️",
        "recycle" to "♻️",
        "infinity" to "♾️",
        "peace" to "☮️",
        "atom" to "⚛️",
        "hourglass" to "⌛",
        "timer" to "⏱️",
        "alarm_clock" to "⏰",
        "stopwatch" to "⏱️",
        "clock" to "🕐",
        "umbrella" to "☂️",
        "comet" to "☄️",
        "volcano" to "🌋",
        "earth_africa" to "🌍",
        "earth_asia" to "🌏",
        "globe_with_meridians" to "🌐",
        "moyai" to "🗿",
        "hot_pepper" to "🌶️",
        "corn" to "🌽",
        "lemon" to "🍋",
        "pineapple" to "🍍",
        "mango" to "🥭",
        "coconut" to "🥥",
        "broccoli" to "🥦",
        "carrot" to "🥕",
        "garlic" to "🧄",
        "onion" to "🧅",
        "cherries" to "🍒",
        "kiwi" to "🥝",
        "tomato" to "🍅",
        "eggplant" to "🍆",
        "peanuts" to "🥜",
        "bread" to "🍞",
        "cheese" to "🧀",
        "meat_on_bone" to "🍖",
        "ramen" to "🍜",
        "sushi" to "🍣",
        "dumpling" to "🥟",
        "champagne" to "🍾",
        "cocktail" to "🍸",
        "tropical_drink" to "🍹",
        "milk" to "🥛",
        "baby_bottle" to "🍼",
        "candy" to "🍬",
        "lollipop" to "🍭",
        "doughnut" to "🍩",
        "pie" to "🥧",
        "birthday" to "🎂",
        "cupcake" to "🧁",

        // Additional popular ones
        "thumbs_up" to "👍",
        "thumbs_down" to "👎",
        "fingers_crossed" to "🤞",
        "pinched_fingers" to "🤌",
        "palms_up_together" to "🤲",
        "nail_care" to "💅",
        "selfie" to "🤳",
        "dancer" to "💃",
        "man_dancing" to "🕺",
        "levitate" to "🕴️",
        "sleeping" to "😴",
        "drooling_face" to "🤤",
        "nauseated_face" to "🤢",
        "sneezing_face" to "🤧",
        "face_with_thermometer" to "🤒",
        "nerd" to "🤓",
        "cowboy" to "🤠",
        "detective" to "🕵️",
        "astronaut" to "🧑‍🚀",
        "santa" to "🎅",
        "angel" to "👼",
        "princess" to "👸",
        "superhero" to "🦸",
        "mage" to "🧙",
        "fairy" to "🧚",
        "vampire" to "🧛",
        "zombie" to "🧟",
        "mermaid" to "🧜",
        "elf" to "🧝",
        "baby" to "👶",
        "woman" to "👩",
        "man" to "👨",
        "child" to "🧒",
        "older_adult" to "🧓",
        "person_frowning" to "🙍",
        "person_shrugging" to "🤷",
        "person_facepalming" to "🤦",
        "shrug" to "🤷",
        "facepalm" to "🤦",
    )

    // Sort emoticon keys longest-first so ":-)" matches before ":)"
    private val sortedEmoticonKeys = EMOTICON_MAP.keys.sortedByDescending { it.length }

    // Compile emoticon regex once
    private val EMOTICON_REGEX: Regex = run {
        val pattern = sortedEmoticonKeys.joinToString("|") { Regex.escape(it) }
        """(?<=^|\s)(?:$pattern)(?=${'$'}|\s|[.,!?;:\])"'()])""".toRegex()
    }

    // Compile shortcode regex once: :name or :name: (optional closing colon)
    private val SHORTCODE_REGEX: Regex =
        """(?<=^|\s):([a-z0-9_+-]+):?(?=${'$'}|\s|[.,!?;\])"'()])""".toRegex()

    fun convertEmojis(text: String): String {
        var result = EMOTICON_REGEX.replace(text) { match ->
            EMOTICON_MAP[match.value] ?: match.value
        }
        result = SHORTCODE_REGEX.replace(result) { match ->
            SHORTCODE_MAP[match.groupValues[1]] ?: match.value
        }
        return result
    }
}
