export { default as authRoutes } from './auth.js';
export { default as usersRoutes } from './users.js';
export { default as contactsRoutes } from './contacts.js';
export { default as messagesRoutes } from './messages.js';
export { default as roomsRoutes } from './rooms.js';
export { default as adminRoutes } from './admin.js';
export { default as apkRoutes } from './apk.js';
export { default as notesRoutes } from './notes.js';
export { default as labelsRoutes } from './labels.js';
