import {
  Phone,
  Video,
  Settings,
  Globe,
  LogOut,
  Users,
  PhoneOff,
  Lock,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Loader2,
  Send,
  Image as ImageIcon,
  Paperclip,
  MoreVertical,
  X,
  Check,
  CheckCheck,
} from 'lucide-react';

export const icons = {
  phone: Phone,
  video: Video,
  settings: Settings,
  server: Globe,
  logout: LogOut,
  users: Users,
  phoneOff: PhoneOff,
  lock: Lock,
  mic: Mic,
  micOff: MicOff,
  camera: Camera,
  cameraOff: CameraOff,
  loader: Loader2,
  send: Send,
  image: ImageIcon,
  attachment: Paperclip,
  moreOptions: MoreVertical,
  close: X,
  check: Check,
  checkCheck: CheckCheck,
} as const;

export type IconName = keyof typeof icons;
